name: flutter_module
description: An example Flutter module.
version: 1.0.0+1

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  get_it: ^7.7.0
  lottie: ^3.3.2
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  espresso: ">=0.2.0 <0.5.0"

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: dev.nabrajkhadka.example.flutter_module
    iosBundleIdentifier: dev.nabrajkhadka.example.flutterModule
